from types import TracebackType
from typing import Optional, Type

class CaskError(Exception): ...
class NotReadyError(CaskError): ...
class CustomerNotFoundError(CaskError): ...
class FeatureNotFoundError(CaskError): ...
class WrongTypeError(CaskError): ...
class AuthError(CaskError): ...
class NetworkError(CaskError): ...
class InvalidSnapshotError(CaskError): ...

class Config:
    api_key: str
    base_url: Optional[str]
    poll_interval: float
    debug: bool
    def __init__(
        self,
        api_key: str,
        base_url: Optional[str] = None,
        poll_interval: float = 30.0,
        debug: bool = False,
    ) -> None: ...

class Client:
    def __init__(self, config: Config) -> None: ...
    def wait_until_ready(self, timeout: float = 5.0) -> None: ...
    def is_ready(self) -> bool: ...
    def check_bool(self, customer: str, feature: str) -> bool: ...
    def check_numeric(self, customer: str, feature: str) -> Optional[float]: ...
    def check_enum(self, customer: str, feature: str) -> Optional[str]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Client": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Optional[TracebackType],
    ) -> None: ...
