/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Client {
  constructor(config: Config)
  /** Resolves when the first snapshot has loaded; rejects after `timeout` seconds (default 5). */
  waitUntilReady(timeout?: number | undefined | null): Promise<void>
  isReady(): boolean
  checkBool(customer: string, feature: string): boolean
  /** Returns null if not granted, and Infinity for unlimited. */
  checkNumeric(customer: string, feature: string): number | null
  /** Returns null if not granted. */
  checkEnum(customer: string, feature: string): string | null
  close(): void
}

export interface Config {
  apiKey: string
  /** Defaults to http://127.0.0.1:8080. */
  baseUrl?: string
  /** Seconds between snapshot refreshes. Defaults to 30. */
  pollInterval?: number
  /** Print debug messages to stderr. Defaults to false. */
  debug?: boolean
}
